# Generated by Django 5.2.7 on 2025-10-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.CharField(max_length=128),
        ),
    ]
